export default {
    state() {
        return {
            transactions: [
                {
                    "BeginDate": "2010-03-12T10:00:00.000Z",
                    "EndDate": "2010-03-13T10:00:00.000Z",
                    "TransDate": "2010-03-12T10:00:00.000Z",
                    "TransType": "+",
                    "DepName": "ООО \"Финансовая Компания Восток-Инвест\"",
                    "AccNumber": "L-101-1001",
                    "AccTypeName": "Текущий счет",
                    "CurrIN": "USD",
                    "CurrName": "Доллар США",
                    "Quantity": 50000.75,
                    "QuantityStop": 0,
                    "OrderCodeName": "Оплата услуг",
                    "Corr": "АО \"Коммерческий банк Север\""
                },
                {
                    "BeginDate": "2011-07-21T14:30:00.000Z",
                    "EndDate": "2011-07-22T14:30:00.000Z",
                    "TransDate": "2011-07-21T14:30:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Южный Финансовый Холдинг\"",
                    "AccNumber": "L-202-2042",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "EUR",
                    "CurrName": "Евро",
                    "Quantity": 25000.30,
                    "QuantityStop": 0,
                    "OrderCodeName": "Покупка оборудования",
                    "Corr": ""
                },
                {
                    "BeginDate": "2012-12-05T09:45:00.000Z",
                    "EndDate": "2012-12-06T09:45:00.000Z",
                    "TransDate": "2012-12-05T09:45:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"Инвестиционная Компания Центр-Капитал\"",
                    "AccNumber": "L-303-3075",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "KGS",
                    "CurrName": "Кыргызский сом",
                    "Quantity": 900000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Инвестиции",
                    "Corr": ""
                },
                {
                    "BeginDate": "2013-04-11T12:00:00.000Z",
                    "EndDate": "2013-04-12T12:00:00.000Z",
                    "TransDate": "2013-04-11T12:00:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Финансовая Корпорация Альфа-Капитал\"",
                    "AccNumber": "L-404-4091",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "RUB",
                    "CurrName": "Российский рубль",
                    "Quantity": 70000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Оплата поставок",
                    "Corr": ""
                },
                {
                    "BeginDate": "2014-06-18T08:15:00.000Z",
                    "EndDate": "2014-06-19T08:15:00.000Z",
                    "TransDate": "2014-06-18T08:15:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"Западный Финансовый Альянс\"",
                    "AccNumber": "L-505-5083",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "JPY",
                    "CurrName": "Японская иена",
                    "Quantity": 800000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Финансовые операции",
                    "Corr": ""
                },
                {
                    "BeginDate": "2015-11-23T16:40:00.000Z",
                    "EndDate": "2015-11-24T16:40:00.000Z",
                    "TransDate": "2015-11-23T16:40:00.000Z",
                    "TransType": "+",
                    "DepName": "ЗАО \"Международный Финансовый Центр\"",
                    "AccNumber": "L-606-6112",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "GBP",
                    "CurrName": "Фунт стерлингов",
                    "Quantity": 45000.50,
                    "QuantityStop": 0,
                    "OrderCodeName": "Капиталовложение",
                    "Corr": ""
                },
                {
                    "BeginDate": "2016-03-11T10:15:00.000Z",
                    "EndDate": "2016-03-12T10:15:00.000Z",
                    "TransDate": "2016-03-11T10:15:00.000Z",
                    "TransType": "-",
                    "DepName": "ОсОО \"Альянс Финансовый Групп\"",
                    "AccNumber": "L-707-7154",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "CHF",
                    "CurrName": "Швейцарский франк",
                    "Quantity": 30000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Выплата по кредиту",
                    "Corr": ""
                },
                {
                    "BeginDate": "2017-09-22T15:50:00.000Z",
                    "EndDate": "2017-09-23T15:50:00.000Z",
                    "TransDate": "2017-09-22T15:50:00.000Z",
                    "TransType": "+",
                    "DepName": "ООО \"Восточный Финансовый Холдинг\"",
                    "AccNumber": "L-808-8182",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "CAD",
                    "CurrName": "Канадский доллар",
                    "Quantity": 60000.45,
                    "QuantityStop": 0,
                    "OrderCodeName": "Возврат депозита",
                    "Corr": ""
                },
                {
                    "BeginDate": "2018-12-03T14:30:00.000Z",
                    "EndDate": "2018-12-04T14:30:00.000Z",
                    "TransDate": "2018-12-03T14:30:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Финансовый Центр Капиталовложений\"",
                    "AccNumber": "L-909-9192",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "AUD",
                    "CurrName": "Австралийский доллар",
                    "Quantity": 10000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Оплата контрактов",
                    "Corr": ""
                },
                {
                    "BeginDate": "2019-05-19T11:20:00.000Z",
                    "EndDate": "2019-05-20T11:20:00.000Z",
                    "TransDate": "2019-05-19T11:20:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"Западный Финансовый Центр\"",
                    "AccNumber": "L-1010-10104",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "NZD",
                    "CurrName": "Новозеландский доллар",
                    "Quantity": 20000.75,
                    "QuantityStop": 0,
                    "OrderCodeName": "Капиталовложение",
                    "Corr": ""
                },
                {
                    "BeginDate": "2010-08-12T10:00:00.000Z",
                    "EndDate": "2010-08-13T10:00:00.000Z",
                    "TransDate": "2010-08-12T10:00:00.000Z",
                    "TransType": "+",
                    "DepName": "ООО \"Финансовый Альянс Восток\"",
                    "AccNumber": "L-110-1101",
                    "AccTypeName": "Текущий счет",
                    "CurrIN": "USD",
                    "CurrName": "Доллар США",
                    "Quantity": 55000.85,
                    "QuantityStop": 0,
                    "OrderCodeName": "Оплата товаров",
                    "Corr": "АО \"Коммерческий банк Восток\""
                },
                {
                    "BeginDate": "2011-06-21T14:30:00.000Z",
                    "EndDate": "2011-06-22T14:30:00.000Z",
                    "TransDate": "2011-06-21T14:30:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Северный Финансовый Холдинг\"",
                    "AccNumber": "L-220-2142",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "EUR",
                    "CurrName": "Евро",
                    "Quantity": 65000.20,
                    "QuantityStop": 0,
                    "OrderCodeName": "Закупка оборудования",
                    "Corr": ""
                },
                {
                    "BeginDate": "2012-11-15T09:45:00.000Z",
                    "EndDate": "2012-11-16T09:45:00.000Z",
                    "TransDate": "2012-11-15T09:45:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"ИнвестГрупп\"",
                    "AccNumber": "L-330-3175",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "KGS",
                    "CurrName": "Кыргызский сом",
                    "Quantity": 600000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Финансовые инвестиции",
                    "Corr": ""
                },
                {
                    "BeginDate": "2013-03-11T12:00:00.000Z",
                    "EndDate": "2013-03-12T12:00:00.000Z",
                    "TransDate": "2013-03-11T12:00:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Финансовая Компания Альфа-Восток\"",
                    "AccNumber": "L-440-4191",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "RUB",
                    "CurrName": "Российский рубль",
                    "Quantity": 90000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Поставка материалов",
                    "Corr": ""
                },
                {
                    "BeginDate": "2014-05-18T08:15:00.000Z",
                    "EndDate": "2014-05-19T08:15:00.000Z",
                    "TransDate": "2014-05-18T08:15:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"Финансовый Альянс\"",
                    "AccNumber": "L-550-5183",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "JPY",
                    "CurrName": "Японская иена",
                    "Quantity": 950000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Валютные операции",
                    "Corr": ""
                },
                {
                    "BeginDate": "2015-10-23T16:40:00.000Z",
                    "EndDate": "2015-10-24T16:40:00.000Z",
                    "TransDate": "2015-10-23T16:40:00.000Z",
                    "TransType": "+",
                    "DepName": "ЗАО \"Финансовый Центр Восток\"",
                    "AccNumber": "L-660-6112",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "GBP",
                    "CurrName": "Фунт стерлингов",
                    "Quantity": 75000.10,
                    "QuantityStop": 0,
                    "OrderCodeName": "Инвестиционные операции",
                    "Corr": ""
                },
                {
                    "BeginDate": "2016-04-11T10:15:00.000Z",
                    "EndDate": "2016-04-12T10:15:00.000Z",
                    "TransDate": "2016-04-11T10:15:00.000Z",
                    "TransType": "-",
                    "DepName": "ОсОО \"Альфа-Групп\"",
                    "AccNumber": "L-770-7154",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "CHF",
                    "CurrName": "Швейцарский франк",
                    "Quantity": 50000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Погашение кредита",
                    "Corr": ""
                },
                {
                    "BeginDate": "2017-08-22T15:50:00.000Z",
                    "EndDate": "2017-08-23T15:50:00.000Z",
                    "TransDate": "2017-08-22T15:50:00.000Z",
                    "TransType": "+",
                    "DepName": "ООО \"Финансовый Холдинг\"",
                    "AccNumber": "L-880-8182",
                    "AccTypeName": "Депозитный счет",
                    "CurrIN": "CAD",
                    "CurrName": "Канадский доллар",
                    "Quantity": 95000.45,
                    "QuantityStop": 0,
                    "OrderCodeName": "Возврат средств",
                    "Corr": ""
                },
                {
                    "BeginDate": "2018-11-03T14:30:00.000Z",
                    "EndDate": "2018-11-04T14:30:00.000Z",
                    "TransDate": "2018-11-03T14:30:00.000Z",
                    "TransType": "-",
                    "DepName": "ЗАО \"Центр Финансовых Операций\"",
                    "AccNumber": "L-990-9192",
                    "AccTypeName": "Сберегательный счет",
                    "CurrIN": "AUD",
                    "CurrName": "Австралийский доллар",
                    "Quantity": 8000,
                    "QuantityStop": 0,
                    "OrderCodeName": "Оплата контрактов",
                    "Corr": ""
                },
                {
                    "BeginDate": "2019-06-19T11:20:00.000Z",
                    "EndDate": "2019-06-20T11:20:00.000Z",
                    "TransDate": "2019-06-19T11:20:00.000Z",
                    "TransType": "+",
                    "DepName": "ОсОО \"Финансовый Центр Запад\"",
                    "AccNumber": "L-1011-10104",
                    "AccTypeName": "ДС в номинальном держании",
                    "CurrIN": "NZD",
                    "CurrName": "Новозеландский доллар",
                    "Quantity": 40000.75,
                    "QuantityStop": 0,
                    "OrderCodeName": "Инвестиции",
                    "Corr": ""
                }
            ]
            
        };
    },
    getters: {
        extractCash: state => state.transactions
    }
};
