export default{
    state() {
        return {
            orders: []
        };
    },
    mutations: {
        setOrders(state, orders) {
            state.orders = orders;
        }
    },
    actions: {
        fetchOrders({ commit }) {
            const orders = [
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02250529",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1205400,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02251016",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1210000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260212",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1900000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260422",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1000000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GD052241014",
                    "SecTypeName": "гос. казначейский вексель",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 500000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02250529",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1205400,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02251016",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1210000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260212",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1900000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260422",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1000000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GD052241014",
                    "SecTypeName": "гос. казначейский вексель",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 500000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02250529",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1205400,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02251016",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1210000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260212",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1900000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GBA02260422",
                    "SecTypeName": "гос.казначейская облигация",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 1000000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GD052241014",
                    "SecTypeName": "гос. казначейский вексель",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 500000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                },
                {
                    "BeginDate": "2024-06-05T16:13:33.000Z",
                    "EndDate": "2024-06-07T16:13:37.000Z",
                    "TransDate": "2024-06-05T16:13:33.000Z",
                    "TransType": "+",
                    "DepName": "Агентство по защите депозитов Кыргызской Республики",
                    "AccNumber": "1-3001-2012",
                    "AccTypeName": "ЦБ в собственности для ТС",
                    "SecIN": "GD052241118",
                    "SecTypeName": "гос. казначейский вексель",
                    "EmitentName": "Министерство финансов КР",
                    "Quantity": 500000,
                    "QuantityStop": 0,
                    "OrderCodeName": "",
                    "Corr": ""
                }
            ];
            commit('setOrders', orders);
        }
    },
    getters: {
        orders: state => state.orders
    }
};

